run:
  modules-download-mode: vendor
linters-settings:
  goconst:
    min-len: 2
    min-occurrences: 2
  gocritic:
    enabled-tags:
      - diagnostic
      - experimental
      - opinionated
      - performance
      - style
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: github.com/afarbos/aoc/
  golint:
    min-confidence: 0
  govet:
    check-shadowing: true
  maligned:
    suggest-new: true
  prealloc:
    for-loops: true
  unparam:
    check-exported: true
  whitespace:
    multi-if: true
    multi-func: true
linters:
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofmt
    - goimports
    - golint
    - gomodguard
    - goprintffuncname
    - interfacer
    - lll
    - maligned
    - misspell
    - nakedret
    - prealloc
    - rowserrcheck
    - scopelint
    - stylecheck
    - unconvert
    - unparam
    - whitespace
    - wsl
