run:
  modules-download-mode: vendor
linters-settings:
  gocyclo:
    min-complexity: 15
  goimports:
    local-prefixes: github.com/afarbos/aoc/
  govet:
    check-shadowing: true
linters:
  enable:
    - bodyclose
    - depguard
    - dogsled
    - dupl
    - funlen
    - goconst
    - gocritic
    - gocyclo
    - godot
    - godox
    - gofmt
    - goimports
    - golint
    - gomodguard
    - goprintffuncname
    - interfacer
    - lll
    - maligned
    - misspell
    - nakedret
    - prealloc
    - rowserrcheck
    - scopelint
    - stylecheck
    - unconvert
    - unparam
    - whitespace
    - wsl
